name: rbbrainhack
dependencies:
  - python=2.7
  - jupyter
  - scikit-learn
  - numpy
  - scipy
  - matplotlib
  - pip:
    - git+git://github.com/janfreyberg/pySTATIS
    - git+git://github.com/janfreyberg/mapalign
    - nibabel
    - nilearn
    - matlab_kernel
